re = require "re"

require "src/utils"
require "src/chords"
require "src/fields"
require "src/keys"
require "src/lyrics"
require "src/macro"
require "src/parts"
require "src/notes"
require "src/directives"
require "src/bar"
require "src/stream"
require "src/compile"
require "src/tools"
require "src/emit_abc"
abclua = require "src/parse_abc"
require "src/register_directives"
return abclua