-- concatenates entire source into one lua file

local files = {"utils", "keys", "parts",  "lyrics", "chords", "stream", "macro", "directives", "fields", "bar", "notes", "emit_abc", "tools", "tuplets", "pitches", "compile","master_parser","parse_abc", "parse_note", "meter_tempo", "register_directives", "symbol_line"}



result = {}
table.insert(result, [[
-- ABC Lua single file: autogenerated from source files
-- DO NOT EDIT; regenerate using make_abclua.lua
--
-- 
-- Simple ABC parsing for Lua. This library can read a reasonable
-- subset of ABC and generate tables representing the song structure.
--
-- Requires: 
--     Lua 5.1+ http://www.lua.org
--     LPeg http://www.inf.puc-rio.br/~roberto/lpeg/
--
-- License: BSD 3 clause license
--  
-- * Copyright (c) 2013, John Williamson
-- * All rights reserved.
-- *
-- * Redistribution and use in source and binary forms, with or without
-- * modification, are permitted provided that the following conditions are met:
-- *     * Redistributions of source code must retain the above copyright
-- *       notice, this list of conditions and the following disclaimer.
-- *     * Redistributions in binary form must reproduce the above copyright
-- *       notice, this list of conditions and the following disclaimer in the
-- *       documentation and/or other materials provided with the distribution.
-- *     * Neither the name of the <organization> nor the
-- *       names of its contributors may be used to endorse or promote products
-- *       derived from this software without specific prior written permission.
-- *
-- * THIS SOFTWARE IS PROVIDED BY <copyright holder> ``AS IS'' AND ANY
-- * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- * DISCLAIMED. IN NO EVENT SHALL <copyright holder> BE LIABLE FOR ANY
-- * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-- * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-- * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-- * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-- * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.**
--

]])

-- uncomment the following line to enable strict (no globals) testing
--table.insert(result, "require 'strict'")

table.insert(result,'local re = require "re"\n')
functions = {}    

for i,v in ipairs(files) do    
    local f = io.open('src/'..v..'.lua', 'r')
    local contents = f:read('*a')
    f:close()
            
    -- make all functions local
    for fn in contents:gmatch('\nfunction ([^(]+)([^\n]*)\n') do
        table.insert(functions, fn)
    end
            
    -- remove the original return abclua
    contents = contents:gsub('\nreturn abclua\n', '\n')
    
    table.insert(result,'\n')
    table.insert(result,'--\n')
    table.insert(result,'-- From source file: ' .. v..'.lua'..'\n')
    table.insert(result,'--\n')
    table.insert(result,contents)               
    table.insert(result,'\n\n')
end

-- add in local definitions for functions
-- for i,v in ipairs(functions) do
    -- table.insert(result, 3, 'local '..v..'\n')
-- end

table.insert(result, 3, 'module(...,package.seeall)')

-- add in final return
table.insert(result,'return abclua')

local out = io.open('abclua_all.lua', 'w')
out:write(table.concat(result))
out:close()
